In [1]:
import selenium
import pandas as pd
from selenium import webdriver
import requests
from bs4 import BeautifulSoup

In [2]:
driver = webdriver.Chrome("chromedriver.exe")

# 1. Write a python program which searches all the product under a particular product verticalfrom www.amazon.in. The product verticals to be searched will be taken as input from user.For e.g. If user input is ‘guitar’. Then search for guitars.
# 2. In the above question, now scrape the following details of each product listed in first 3 pages of your search results and save it in a data frame and csv. In case if any product vertical has less than 3 pages in search results then scrape all the products available under that product vertical. Details to be scraped are: "Brand Name", "Name of the Product", "Rating", "No. of Ratings", "Price", "Return/Exchange", "Expected Delivery", "Availability", "Other Details" and “Product URL”. In case, if any of the details are missing for any of the product then replace it by “-“

In [88]:
url = "https://www.amazon.in/"
driver.get(url)

In [89]:
var=input("")

mouse

In [90]:
search_job=driver.find_element_by_id("twotabsearchtextbox")

In [91]:
search_job.send_keys(var)

In [92]:
btn=driver.find_element_by_id("nav-search-submit-button")
btn.click()

In [93]:
Brand=[]
Name=[]
Rating=[]
no_Ratings=[]
Price=[]
Return_Exchange=[]
expected=[]
Availability=[] 
Other=[]
product_url=[]

In [95]:
urls=[]
for i in driver.find_elements_by_xpath('//a[@class="a-link-normal a-text-normal"]'):
    urls.append(i.get_attribute('href'))

In [104]:
len(urls)

27

In [105]:
for i in urls:
    driver.get(i)
    try:
        for i in driver.find_elements_by_xpath('//span[@class="a-size-large product-title-word-break"]'):
            Name.append(i.text)
    except:
        None 
        
    try:
        for i in driver.find_elements_by_xpath('//span[@class="a-size-medium a-color-success"]'):
            Availability.append(i.text)
    except:
        None
   

    try:
        for i in driver.find_elements_by_xpath('//div[@class="a-row a-spacing-medium averageStarRatingNumerical"]'):
            no_Ratings.append(i.text)
    except:
        None
        
        
    try:
        for i in driver.find_elements_by_xpath('//div[@class="a-fixed-left-grid-col aok-align-center a-col-right"]'):
            Rating.append(i.text)
    except:
        None
        
    try:
        for i in driver.find_elements_by_xpath('/html/body/div[2]/div[2]/div[5]/div[4]/div[4]/div[11]/div/div/b'):
            expected.append(i.text)
    except:
        None
    try:
        for i in driver.find_elements_by_xpath('//td[@class="a-span12"]'):
            Price.append(i.text)
    except:
        None

In [120]:
Brand=[]

In [121]:
for i in urls:
    driver.get(i)
    try:
        for i in driver.find_elements_by_xpath('//table[@class="a-normal a-spacing-micro"]//td'):
            if i.text is None:
                Brand.append("--")
            else:
                Brand.append(i.text)
    except:
        Brand.append("-")

In [129]:
other=Brand[1::10]

In [130]:
brand=Brand[3::10]

In [117]:
for i in urls:
    driver.get(i)
    try:
        for i in driver.find_elements_by_xpath('//div[@id="RETURNS_POLICY"]//a'):
            Return_Exchange.append(i.text)
    except:
          None

In [131]:
df=pd.DataFrame({"Name":Name,
"Rating":Rating,
"no_Ratings":no_Ratings,
"Price":Price,
"expected":expected,
"Availability":Availability,
"product_url":urls,
"Brand":brand,
"Other":other})

In [133]:
df.head()

,Name,Rating,no_Ratings,Price,expected,Availability,product_url,Brand,Other
0,"Logitech M331 Silent Plus Wireless Mouse, 2.4G...",4.6 out of 5,"6,780 global ratings","₹1,099.00","Friday, Aug 27",In stock.,https://www.amazon.in/gp/slredirect/picassoRed...,Logitech,USB
1,"Logitech M337 Wireless Mouse, Bluetooth, 1000 ...",4.5 out of 5,"6,130 global ratings","₹1,195.00","Wednesday, Aug 25",In stock.,https://www.amazon.in/gp/slredirect/picassoRed...,Logitech,Bluetooth
2,"Lenovo 300 Wired Plug & Play USB Mouse, High R...",4.4 out of 5,"23,304 global ratings",₹299.00 Fulfilled,"Wednesday, Aug 25",In stock.,https://www.amazon.in/Lenovo-GX30M39704-300-US...,Lenovo,USB
3,Dell MS116 1000DPI USB Wired Optical Mouse,4.4 out of 5,"13,092 global ratings",₹299.00 Fulfilled,"Tuesday, Aug 24",In stock.,https://www.amazon.in/Dell-MS116-1000DPI-Wired...,Dell,USB
4,Zebronics Zeb-Transformer-M Optical USB Gaming...,4.4 out of 5,"23,214 global ratings",₹449.00 Fulfilled,"Tuesday, Aug 24",In stock.,https://www.amazon.in/Zebronics-Zeb-Transforme...,ZEBRONICS,USB-A

# 7. Write a program to scrap all the available details of best gaming laptops from digit.in

In [12]:
driver.get("https://www.digit.in/")

In [13]:
i= driver.find_element_by_xpath('/html/body/div[3]/div/div[2]/div[2]/div[4]/ul/li[9]/a')
i.click()

In [6]:
product=[]
seller=[]
price=[]

In [7]:
det=[]

In [8]:
for i in driver.find_elements_by_xpath('//div[@class="Top10-Seller"]//td'):
    det.append(i.text)
for j in range(0,len(det),3):
    product.append(det[j])

for j in range(1,len(det),3):
    if det[j] == "N/A" or det[j] is None:
        seller.append("--")
    else:
        seller.append(det[j])
        
for j in range(2,len(det),3):
    if det[j] == "N/A" or det[j] is None:
        price.append("--")
    else:
        price.append(det[j])

In [ ]:
spec=[]

In [10]:
for i in driver.find_elements_by_xpath('//div[@class="value"]'):
    spec.append(i.text.replace(":",""))

In [9]:

os=[]
display=[]
processor=[]
memory=[]

In [12]:
os=spec[0::4]
display=spec[1::4]
processor=spec[2::4]
memory=spec[3::4]

In [18]:
df=pd.DataFrame({"Product":product,
             "Seller":seller,
             "price":price,
             "OS":os,
              "Display":display,
           "Processor":processor,
           "Memory":memory})
df

,Product,Seller,price,OS,Display,Processor,Memory
0,Alienware Area 51M R2,--,--,WINDOWS 10 HOME,"17.3"" (1920 X 1080)",10TH GENERATION INTEL® CORE™ I7-10700 | 2.90 GHZ,1 TB SSD/16 GBGB DDR4
1,Alienware m15 R3,--,₹341990,WINDOWS 10 HOME,"15.6"" (3840 X 2160)",10TH GENERATION INTEL® CORE™ I9-10980HK | NA,1 TB SSD/16 GBGB DDR4
2,ASUS ROG Strix Scar 15,--,--,WINDOWS 10 HOME,"15.6"" (1920 X 1080)",AMD RYZEN™ 9 5900HX | 3.3 GHZ,1 TB SSD/16 GBGB DDR4
3,Asus ROG Zephyrus G14,amazon,₹164990,WINDOWS 10 HOME,"14"" (1920 X 1080)",AMD 3RD GENERATION RYZEN 9 | 3.3 GHZ,1 TB SSD/16 GBGB DDR4
4,Lenovo Legion 5i,amazon,₹76988,WINDOWS 10 PRO,"15.6"" (1920 X 1080)",10TH GENERATION INTEL® CORE™ I5-10300H | 2.50 GHZ,1 TB SSD/16 GBGB DDR4
5,ASUS ROG ZEPHYRUS DUO 15,amazon,₹185000,WINDOWS 10,"15.6"" (3840 X 1100)",INTEL CORE I7 10TH GEN 10875H | NA,512 GB SSD/4 GBGB DDR4
6,Acer Aspire 7 gaming,amazon,₹64370,WINDOWS 10 HOME,"15.6"" (1920 X 1080)",AMD RYZEN™ 5-5500U HEXA-CORE | NA,512 GB SSD/8 GBGB DDR4

# Write a python program to scrape the details for all billionaires from www.forbes.com. 
Details to be scrapped: “Rank”, “Name”, “Net worth”, “Age”, “Citizenship”, “Source”, 
“Industry”

In [232]:
driver.get("https://www.forbes.com/?sh=3ac8c6bc2254")

In [233]:
for i in driver.find_elements_by_xpath('//li[@data-title="Billionaires"]//a'):
    urls.append(i.get_attribute('href'))

In [234]:
rank=[]
name=[]
net=[]
age=[]
country=[]
source=[]
industry=[]

In [5]:


while True:
    try:
        for j in driver.find_elements_by_xpath('//div[@class="rank"]'):
            rank.append(j.text.replace(".",""))
    
        for j in driver.find_elements_by_xpath('//div[@class="personName"]'):
            name.append(j.text)
    
        for j in driver.find_elements_by_xpath('//div[@class="netWorth"]'):
            net.append(j.text)
    
        for j in driver.find_elements_by_xpath('//div[@class="age"]'):
            age.append(j.text)
    
        for j in driver.find_elements_by_xpath('//div[@class="countryOfCitizenship"]'):
            country.append(j.text)
    
        for j in driver.find_elements_by_xpath('//div[@class="source"]'):
            source.append(j.text)
    
        for j in driver.find_elements_by_xpath('//div[@class="category"]'):
            industry.append(j.text) 
            
        next=driver.find_element_by_xpath('//div[@class="next-page"]')
        next.click()
        
        
    except:
        print("no more pages")
        break

no more pages

In [7]:
df=pd.DataFrame({"RANK":rank,
                 "NAME":name,
                 "NET_WORTH":net,
                 "AGE":age,
                 "COUNTRY/TERRITORY":country,
                 "SOURCE":source,
                 "INDUSTRY":industry
})
df

,RANK,NAME,NET_WORTH,AGE,COUNTRY/TERRITORY,SOURCE,INDUSTRY
0,1,Jeff Bezos,$177 B,57,United States,Amazon,Technology
1,2,Elon Musk,$151 B,49,United States,"Tesla, SpaceX",Automotive
2,3,Bernard Arnault & family,$150 B,72,France,LVMH,Fashion & Retail
3,4,Bill Gates,$124 B,65,United States,Microsoft,Technology
4,5,Mark Zuckerberg,$97 B,36,United States,Facebook,Technology
...,...,...,...,...,...,...,...
2750,2674,Daniel Yong Zhang,$1 B,49,China,e-commerce,Technology
2751,2674,Zhang Yuqiang,$1 B,65,China,Fiberglass,Manufacturing
2752,2674,Zhao Meiguang,$1 B,58,China,gold mining,Metals & Mining
2753,2674,Zhong Naixiong,$1 B,58,China,conglomerate,Diversified
2754,2674,Zhou Wei family,$1 B,54,China,Software,Technology

# Write a python program to search for a smartphone(e.g.: Oneplus Nord, pixel 4A, etc.) on www.flipkart.com and scrape following details for all the search results displayed on 1st page. Details to be scraped: “Brand Name”, “Smartphone name”, “Colour”, “RAM”, “Storage(ROM)”, “Primary Camera”, “Secondary Camera”, “Display Size”, “Display Resolution”, “Processor”, “Processor Cores”, “Battery Capacity”, “Price”, “Product URL”. Incase if any of the details is missing then replace it by “- “. Save your results in a dataframe and CSV.

In [137]:
driver.get("https://www.flipkart.com/")

In [138]:
var=input()

iphone

In [139]:
search=driver.find_element_by_xpath("/html/body/div[1]/div/div[1]/div[1]/div[2]/div[2]/form/div/div/input")
search.send_keys(var)

In [140]:
btn=driver.find_element_by_class_name("L0Z3Pu")
btn.click()

In [141]:
urls=[]
for i in driver.find_elements_by_xpath('//a[@class="_1fQZEK"]'):
    urls.append(i.get_attribute('href'))

In [148]:
name=[]

In [151]:
for i in urls:
    driver.get(i)
    try:
        for i in driver.find_elements_by_xpath('//span[@class="B_NuCI"]'):
            name.append(i.text)
    except:
          None

In [169]:
o=[]

In [170]:
for i in urls:
    driver.get(i)
    try:
        for i in driver.find_elements_by_xpath('/html/body/div[1]/div/div[3]/div[1]/div[2]/div[8]/div[1]/div/div[2]/ul/li[1]'):
            o.append(i.text)
    except:
          None

In [171]:
d=[]
f=[]
g=[]
h=[]
p=[]

In [172]:
for i in urls:
    driver.get(i)
    try:
        for i in driver.find_elements_by_xpath('/html/body/div[1]/div/div[3]/div[1]/div[2]/div[6]/div/div[2]/div[1]/ul/li[2]/a'):
            d.append(i.text)
    except:
          None

In [175]:
for i in urls:
    driver.get(i)
    try:
        for i in driver.find_elements_by_xpath('/html/body/div[1]/div/div[3]/div[1]/div[2]/div[8]/div[1]/div/div[2]/ul/li[3]'):
            f.append(i.text)
    except:
          None

In [176]:
for i in urls:
    driver.get(i)
    try:
        for i in driver.find_elements_by_xpath('/html/body/div[1]/div/div[3]/div[1]/div[2]/div[8]/div[1]/div/div[2]/ul/li[2]'):
            g.append(i.text)
    except:
          None

In [195]:
for i in urls:
    driver.get(i)
    try:
        for i in driver.find_elements_by_xpath('/html/body/div[1]/div/div[3]/div[1]/div[2]/div[8]/div[1]/div/div[2]/ul/li[4]'):
            h.append(i.text)
    except:
          None

In [178]:
for i in urls:
    driver.get(i)
    try:
        for i in driver.find_elements_by_xpath('/html/body/div[1]/div/div[3]/div[1]/div[2]/div[8]/div[1]/div/div[2]/ul/li[7]'):
            p.append(i.text)
    except:
          None

In [190]:
price=[]

In [193]:
for i in urls:
    driver.get(i)
    try:
        for i in driver.find_elements_by_xpath('/html/body/div[1]/div/div[3]/div[1]/div[2]/div[2]/div/div[4]/div[1]/div/div[1]'):
            price.append(i.text)
    except:
          None

In [204]:
df=pd.DataFrame({"Brand name":name,
                "Rom":o,
                "Ram":d,
                "Primary Camera":f,
                "Display Size":g,
                "Display Resolution":p,
                "Product_url":urls,
                "Processor":h,
                "Price":price})

In [205]:
df

,Brand name,Rom,Ram,Primary Camera,Display Size,Display Resolution,Product_url,Processor,Price
0,"APPLE iPhone 12 (Blue, 128 GB)",128 GB ROM,128 GB,12MP + 12MP | 12MP Front Camera,15.49 cm (6.1 inch) Super Retina XDR Display,All Screen OLED Display,https://www.flipkart.com/apple-iphone-12-blue-...,A14 Bionic Chip with Next Generation Neural En...,"₹72,999"
1,"APPLE iPhone SE (Black, 128 GB)",128 GB ROM,128 GB,12MP Rear Camera | 7MP Front Camera,11.94 cm (4.7 inch) Retina HD Display,Wireless charging (Works with Qi Chargers | Qi...,https://www.flipkart.com/apple-iphone-se-black...,A13 Bionic Chip with 3rd Gen Neural Engine Pro...,"₹34,999"
2,"APPLE iPhone 12 (White, 128 GB)",128 GB ROM,128 GB,12MP + 12MP | 12MP Front Camera,15.49 cm (6.1 inch) Super Retina XDR Display,All Screen OLED Display,https://www.flipkart.com/apple-iphone-12-white...,A14 Bionic Chip with Next Generation Neural En...,"₹72,999"
3,"APPLE iPhone 12 (Green, 128 GB)",128 GB ROM,128 GB,12MP + 12MP | 12MP Front Camera,15.49 cm (6.1 inch) Super Retina XDR Display,All Screen OLED Display,https://www.flipkart.com/apple-iphone-12-green...,A14 Bionic Chip with Next Generation Neural En...,"₹72,999"
4,"APPLE iPhone 12 (Blue, 64 GB)",64 GB ROM,128 GB,12MP + 12MP | 12MP Front Camera,15.49 cm (6.1 inch) Super Retina XDR Display,All Screen OLED Display,https://www.flipkart.com/apple-iphone-12-blue-...,A14 Bionic Chip with Next Generation Neural En...,"₹67,999"
5,"APPLE iPhone 12 (Purple, 64 GB)",64 GB ROM,128 GB,12MP + 12MP | 12MP Front Camera,15.49 cm (6.1 inch) Super Retina XDR Display,All Screen OLED Display,https://www.flipkart.com/apple-iphone-12-purpl...,A14 Bionic Chip with Next Generation Neural En...,"₹67,999"
6,"APPLE iPhone 12 Mini (Black, 128 GB)",128 GB ROM,128 GB,12MP + 12MP | 12MP Front Camera,13.72 cm (5.4 inch) Super Retina XDR Display,All Screen OLED Display,https://www.flipkart.com/apple-iphone-12-mini-...,A14 Bionic Chip with Next Generation Neural En...,"₹64,999"
7,"APPLE iPhone 12 (Black, 128 GB)",128 GB ROM,128 GB,12MP + 12MP | 12MP Front Camera,15.49 cm (6.1 inch) Super Retina XDR Display,All Screen OLED Display,https://www.flipkart.com/apple-iphone-12-black...,A14 Bionic Chip with Next Generation Neural En...,"₹72,999"
8,"APPLE iPhone 12 (Red, 128 GB)",128 GB ROM,128 GB,12MP + 12MP | 12MP Front Camera,15.49 cm (6.1 inch) Super Retina XDR Display,All Screen OLED Display,https://www.flipkart.com/apple-iphone-12-red-1...,A14 Bionic Chip with Next Generation Neural En...,"₹72,999"
9,"APPLE iPhone 11 (Black, 64 GB)",64 GB ROM,128 GB,12MP + 12MP | 12MP Front Camera,15.49 cm (6.1 inch) Liquid Retina HD Display,All Screen OLED Display,https://www.flipkart.com/apple-iphone-11-black...,A13 Bionic Chip Processor,"₹48,999"
10,"APPLE iPhone 12 (White, 64 GB)",64 GB ROM,128 GB,12MP + 12MP | 12MP Front Camera,15.49 cm (6.1 inch) Super Retina XDR Display,Wireless charging (Works with Qi Chargers | Qi...,https://www.flipkart.com/apple-iphone-12-white...,A14 Bionic Chip with Next Generation Neural En...,"₹67,999"
11,"APPLE iPhone 12 Mini (White, 128 GB)",128 GB ROM,128 GB,12MP Rear Camera | 7MP Front Camera,13.72 cm (5.4 inch) Super Retina XDR Display,All Screen OLED Display,https://www.flipkart.com/apple-iphone-12-mini-...,A14 Bionic Chip with Next Generation Neural En...,"₹64,999"
12,"APPLE iPhone SE (White, 128 GB)",128 GB ROM,128 GB,12MP + 12MP | 12MP Front Camera,11.94 cm (4.7 inch) Retina HD Display,All Screen OLED Display,https://www.flipkart.com/apple-iphone-se-white...,A13 Bionic Chip with 3rd Gen Neural Engine Pro...,"₹34,999"
13,"APPLE iPhone 12 (Black, 64 GB)",64 GB ROM,128 GB,12MP + 12MP | 12MP Front Camera,15.49 cm (6.1 inch) Super Retina XDR Display,All Screen OLED Display,https://www.flipkart.com/apple-iphone-12-black...,A14 Bionic Chip with Next Generation Neural En...,"₹67,999"
14,"APPLE iPhone 12 (Green, 64 GB)",64 GB ROM,128 GB,12MP + 12MP | 12MP Front Camera,15.49 cm (6.1 inch) Super Retina XDR Display,Wireless charging (Works with Qi Chargers | Qi...,https://www.flipkart.com/apple-iphone-12-green...,A14 Bionic Chip with Next Generation Neural En...,"₹67,999"
15,"APPLE iPhone 12 (Purple, 256 GB)",256 GB ROM,128 GB,12MP Rear Camera | 7MP Front Camera,15.49 cm (6.1 inch) Super Retina XDR Display,Wireless charging (Works with Qi Chargers | Qi...,https://www.flipkart.com/apple-iphone-12-purpl...,A14 Bionic Chip with Next Generation Neural En...,"₹82,999"
16,"APPLE iPhone SE (Red, 128 GB)",128 GB ROM,128 GB,12MP + 12MP | 12MP Front Camera,11.94 cm (4.7 inch) Retina HD Display,All Screen OLED Display,https://www.flipkart.com/apple-iphone-se-red-1...,A13 Bionic Chip with 3rd Gen Neural Engine Pro...,"₹34,999"
17,"APPLE iPhone 11 (White, 64 GB)",64 GB ROM,128 GB,12MP + 12MP | 12MP Front Camera,15.49 cm (6.1 inch) Liquid Retina HD Display,All Screen OLED Display,https://www.flipkart.com/apple-iphone-11-white...,A13 Bionic Chip Processor,"₹51,999"
18,"APPLE iPhone 11 (Black, 128 GB)",128 GB ROM,128 GB,12MP Rear Camera | 7MP Front Camera,15.49 cm (6.1 inch) Liquid Retina HD Display,All Screen OLED Display,https://www.flipkart.com/apple-iphone-11-black...,A13 Bionic Chip Processor,"₹32,999"

# Write a program to scrap details of all the funding deals for second quarter (i.e. July 20 –September 20) from trak.in

In [60]:
driver.get("https://trak.in/")

In [61]:
ser=driver.find_element_by_xpath("/html/body/div[1]/header/div[2]/div/div/div/div/nav/ul/li[9]/a")
ser.click()

In [62]:
july=[]
for i in driver.find_elements_by_xpath('//table[@class="tablepress tablepress-id-48 dataTable no-footer"]//td'):
    july.append(i.text)

In [63]:
aug=[]
for i in driver.find_elements_by_xpath('//table[@class="tablepress tablepress-id-49 dataTable no-footer"]//td'):
    sept.append(i.text)

In [64]:
sept=[]
for i in driver.find_elements_by_xpath('//table[@class="tablepress tablepress-id-50 dataTable no-footer"]//td'):
    sept.append(i.text)

In [71]:
s_no=[]
date=[]
company=[]
ind=[]
sub=[]
city=[]
name=[]
type_=[]
amount=[]

In [72]:
for i in range(0,len(july),9):
    s_no.append(july[i])
for i in range(1,len(july),9):
    date.append(july[i])
for i in range(2,len(july),9):
    company.append(july[i])
for i in range(3,len(july),9):
    ind.append(july[i])
for i in range(4,len(july),9):
    sub.append(july[i])
for i in range(5,len(july),9):
    city.append(july[i])
for i in range(6,len(july),9):
    name.append(july[i])
for i in range(7,len(july),9):
    type_.append(july[i])
for i in range(8,len(july),9):
    amount.append(july[i])

In [73]:
for i in range(0,len(aug),9):
    s_no.append(aug[i])
for i in range(1,len(aug),9):
    date.append(aug[i])
for i in range(2,len(aug),9):
    company.append(aug[i])
for i in range(3,len(aug),9):
    ind.append(aug[i])
for i in range(4,len(aug),9):
    sub.append(aug[i])
for i in range(5,len(aug),9):
    city.append(aug[i])
for i in range(6,len(aug),9):
    name.append(aug[i])
for i in range(7,len(aug),9):
    type_.append(aug[i])
for i in range(8,len(aug),9):
    amount.append(aug[i])

In [74]:
for i in range(0,len(sept),9):
    s_no.append(sept[i])
for i in range(1,len(sept),9):
    date.append(sept[i])
for i in range(2,len(sept),9):
    company.append(sept[i])
for i in range(3,len(sept),9):
    ind.append(sept[i])
for i in range(4,len(sept),9):
    sub.append(sept[i])
for i in range(5,len(sept),9):
    city.append(sept[i])
for i in range(6,len(sept),9):
    name.append(sept[i])
for i in range(7,len(sept),9):
    type_.append(sept[i])
for i in range(8,len(sept),9):
    amount.append(sept[i])

In [77]:
len(amount)

20

In [82]:
df=pd.DataFrame({"s_no":s_no,"Date":date,
"Company":company,
"Industry":ind,
"Sub-vertical":sub,
"City":city,
"Investor_name":name,
"investment_type":type_,
"Amount":amount})

In [83]:
df

,s_no,Date,Company,Industry,Sub-vertical,City,Investor_name,investment_type,Amount
0,1,15/07/2020,Flipkart,E-commerce,E-commerce,Bangalore,Walmart Inc,M&A,"1,200,000,000"
1,2,16/07/2020,Vedantu,EduTech,Online Tutoring,Bangalore,Coatue Management,Series D,"100,000,000"
2,3,16/07/2020,Crio,EduTech,Learning Platform for Developers,Bangalore,021 Capital,pre-Series A,"934,160"
3,4,14/07/2020,goDutch,FinTech,Group Payments,Mumbai,"Matrix India,Y Combinator, Global Founders Cap...",Seed,"1,700,000"
4,5,13/07/2020,Mystifly,Airfare Marketplace,"Ticketing, Airline Retailing, and Post-Ticketi...",Singapore and Bangalore,Recruit Co. Ltd.,pre-Series B,"3,300,000"
5,6,09/07/2020,JetSynthesys,Gaming and Entertainment,Gaming and Entertainment,Pune,Adar Poonawalla and Kris Gopalakrishnan.,Venture-Series Unknown,"400,000"
6,7,10/07/2020,gigIndia,Marketplace,"Crowd Sourcing, Freelance",Pune,Incubate Fund India and Beyond Next Ventures,pre-Series A,"974,200"
7,8,15/07/2020,PumPumPum,Automotive Rental,Used Car-leasing platform,Gurgaon,Early Adapters Syndicate,Seed,"292,800"
8,9,14/07/2020,FLYX,OTT Player,Streaming Social Network,New York and Delhi,"Raj Mishra, founder of AIT Global Inc",pre-Seed,"200,000"
9,10,13/07/2020,Open Appliances Pvt. Ltd.,Information Technology,Internet-of-Things Security Solutions,Bangalore,Unicorn India Ventures,Venture-Series Unknown,"500,000"
10,1,08/09/2020,Byju’s,EduTech,Online Tutoring,Bangalore,"Silver Lake, Tiger Global, General Atlantic an...",Private Equity,"500,000,000"
11,2,12/09/2020,mCaffeine,Personal Care,Skincare & Haircare,Mumbai,"Amicus Capital Private Equity I LLP, Amicus Ca...",Series B,"3,000,000"
12,3,09/09/2020,Qshala,EduTech,Online Curiosity Platform for Kids,Bangalore,Rainmatter Capital,Angel,"370,000"
13,4,02/09/2020,Winzo,Online Gaming,Online Gaming,New Delhi,"Kalaari Capital Partners, IndigoEdge Managemen...",Series B,"15,500,000"
14,5,09/09/2020,Hippo Video,Video Customer Experience(CX) Platform,Video Customer Experience(CX) Platform,"Newark, Delaware, United States of Amercia","Alpha Wave Incubation, Exfinity Venture Partne...",Series A,"4,500,000"
15,6,07/09/2020,Melorra,E-commerce,Online Jewelry Store,Bangalore,"Shadow Holdings, Lightbox.",Debt Financing,"upto 8,900,000"
16,7,07/09/2020,1mg,E-commerce,Online Pharmacy,Gurgaon,"Gaja Capital, Tata Capital, Partners Group",In Progress,"100,000,000"
17,8,31/08/2020,mfine,HealthTech,On-Demand Healthcare Services,Bangalore,Caretech Pte Inc,Series B,"5,400,000"
18,9,31/08/2020,Apna,Human Resources,Recruitment Platform,Bangalore,Lightspeed India and Sequoia Capital India,Series A,"8,000,000"
19,10,03/09/2020,Railofy,Transportation,WL & RAC protection platform,Mumbai,Chiratae Ventures,Seed,"950,000"

# Write a program to extract at least 500 Comments, Comment upvote and time when comment was posted from any YouTube Video.

In [235]:
driver.get("https://www.youtube.com/watch?v=DKj5m9cSMZs")

In [260]:
comment=[]
time=[]
upvote=[]

In [261]:
for i in driver.find_elements_by_xpath('//yt-formatted-string[@slot="content"]'):
    comment.append(i.text)

In [302]:
a=comment[1::2]
len(a)

520

In [267]:
for i in driver.find_elements_by_xpath('//yt-formatted-string[@class="published-time-text above-comment style-scope ytd-comment-renderer"]'):
    time.append(i.text)

In [268]:
len(time)

520

In [269]:
for i in driver.find_elements_by_xpath('//span[@id="vote-count-middle"]'):
    upvote.append(i.text)

In [270]:
len(upvote)

520

In [278]:
df=pd.DataFrame({"Comment":a[0:500],
                 "Time":time[0:500],
                 "Upvote":upvote[0:500]
                  })

df

                                               Comment          Time Upvote
0    Nadiyon Paar (Let the Music Play Again) is all...  5 months ago    24K
1           ❤️from kerala🌴\nമലയാളീസ് ഉണ്ടോ മക്കളേ..😍✌️  3 months ago   9.8K
2    After watching this song Neha kakkar and Nora ...   1 month ago   1.6K
3    I love how she is fit and not overly skinny, i...   1 month ago     3K
4                                                   💕🔥   1 month ago    273
..                                                 ...           ...    ...
495  No doubt Nora Fatehi is an awesome dancer, but...  5 months ago   3.7K
496  Thank for ruining another master piece... Damn...   1 month ago
497                                          Best song   1 month ago
498                                          Best song   1 month ago
499                 I like this song in a meme vedio 😂   1 month ago      1

[500 rows x 3 columns]

# Write a python program to scrape a data for all available Hostels from https://www.hostelworld.com/ in “London” location. You have to scrape hostel name, distance from city centre, ratings, total reviews, overall reviews, privates from price, dorms from price, facilities and property description.

In [319]:
driver.get("https://www.hostelworld.com/")

In [320]:
search_job=driver.find_element_by_xpath("/html/body/div[1]/div/div/div[1]/div[1]/div/div[2]/div[4]/div/div[2]/div/div[1]/div/input")

In [321]:
search_job.send_keys("London,England")

In [322]:
btn=driver.find_element_by_xpath('//button[@class="button primary large"]')
btn.click()

In [331]:
url=[]
for i in driver.find_elements_by_xpath('//h2[@class="title title-6"]//a'):
    url.append(i.get_attribute("href"))

In [294]:
name=[]
dist=[]
Rat=[]
review=[]
tr=[]
pp=[]
dp=[]
f=[]

In [295]:
for i in driver.find_elements_by_xpath('//div[@class="facilities-label facilities"]'):
    f.append(i.text.replace("\n",""))
    
for i in driver.find_elements_by_xpath('//div[@class="reviews"]'):
    tr.append(i.text)
    
for i in driver.find_elements_by_xpath('//span[@class="description"]'):
    dist.append(i.text)

In [299]:
for i in driver.find_elements_by_xpath('//div[@class="keyword"]//span'):
    review.append(i.text)

In [345]:
e=review[3:]
len(e)

30

In [323]:
for i in driver.find_elements_by_xpath('//div[@class="price-col"]'):
    d.append(i.text)

In [325]:
pp=d[0::2]

In [326]:
dp=d[1::2]

In [301]:
for i in url:
    driver.get(i)
    try:
        rat=driver.find_element_by_xpath('//div[@class="score orange big"]')
        Rat.append(rat.text)
    except:
        Rat.append("-")
        
    try:
        for i in driver.find_elements_by_xpath('//div[@class="title-2"]'):
            name.append(i.text)
    except:
        None

In [330]:
desp=[]

In [332]:
for i in url:
    driver.get(i)
    try:
        rat=driver.find_element_by_xpath('//div[@class="content collapse-content"]')
        desp.append(rat.text)
    except:
        desp.append("-")

In [350]:
df=pd.DataFrame({"hoste_name":name,
"distance_from_city_centre":dist,
"rating":Rat,
"overall_review":e,
"total_review":tr,
"private_room_price":pp,
"dorms_room_price":dp,
"facility":f,
"property_description":desp})

In [351]:
df

,hoste_name,distance_from_city_centre,rating,overall_review,total_review,private_room_price,dorms_room_price,facility,property_description
0,London Waterloo Hostel,Hostel - 0.7km from city centre,7.6,Very Good,2409 Total Reviews,Privates From\nRs6474,Dorms From\nRs1593,Free WiFiFree BreakfastFollows Covid-19 sanita...,COVID-19 Policy Update\n\nIn response to Coron...
1,Barmy Badger Backpackers,Hostel - 5.5km from city centre,10,Superb,1652 Total Reviews,Privates From\nRs5573,Dorms From\nRs2128,Free WiFiFree Breakfast,The Badger is unique for London in that we hav...
2,Wombat's The City Hostel London,Hostel - 3.6km from city centre,9.2,Superb,13140 Total Reviews,Privates From\nRs8044,Dorms From\nRs1852,Free WiFiFollows Covid-19 sanitation guidance,Wombat's The City Hostel London is definitely ...
3,Prime Backpackers Angel,Hostel - 3.6km from city centre,10,Superb,513 Total Reviews,Privates From\nRs6039,Dorms From\nRs2397,Free WiFiFollows Covid-19 sanitation guidance,The hostel is housed in a historic building in...
4,The Walrus Hostel,Hostel - 0.2km from city centre,8.4,Fabulous,3646 Total Reviews,No Privates Available,Dorms From\nRs1277,Free WiFiFollows Covid-19 sanitation guidance,"Great place to stay, comfy bed. Very central l..."
5,St Christopher's Village,Hostel - 1.8km from city centre,8.9,Fabulous,10827 Total Reviews,Privates From\nRs3445,Dorms From\nRs1273,Free WiFiFollows Covid-19 sanitation guidance,COVID 19 Policy Update.\nIn response to Corona...
6,"PubLove @ The Steam Engine, Waterloo",Hostel - 0.5km from city centre,9.0,Superb,189 Total Reviews,Privates From\nRs16414,Dorms From\nRs1368,Free WiFiFollows Covid-19 sanitation guidance,The heart & soul of London backpacking\nPull u...
7,"PubLove @ The Crown, Battersea",Hostel - 4.7km from city centre,6.7,Good,208 Total Reviews,No Privates Available,Dorms From\nRs1094,Free WiFiFollows Covid-19 sanitation guidance,Do London like a local.\nStay just outside the...
8,The Dictionary Hostel,Hostel - 4.1km from city centre,8.7,NEW,3 Total Reviews,Privates From\nRs5471,Dorms From\nRs1824,Free WiFi,Safestay at Elephant & Castle is ideal if you ...
9,Safestay London Elephant & Castle,Hostel - 1.7km from city centre,8.2,Fabulous,3952 Total Reviews,Privates From\nRs4407,Dorms From\nRs1824,Free WiFiFollows Covid-19 sanitation guidance,"Welcome to Urbany Hostel London, our first int..."
10,Urbany Hostel London,Hostel - 5.4km from city centre,10,Superb,106 Total Reviews,Privates From\nRs13131,Dorms From\nRs1368,Free WiFiFollows Covid-19 sanitation guidance,Where it all began - PubLove was born here in ...
11,"PubLove @ The Green Man, Paddington",Hostel - 4.3km from city centre,-,Rating,392 Total Reviews,No Privates Available,Dorms From\nRs3176,Free WiFiFollows Covid-19 sanitation guidance,Mornington Camden Hostel is a high class spaci...
12,Mornington Camden,Hostel - 4.1km from city centre,10,Superb,41 Total Reviews,No Privates Available,Dorms From\nRs1368,Free WiFi,"Food & culture lovers, assemble!\nThe Rose & C..."
13,PubLove @ The Rose & Crown,Hostel - 1.6km from city centre,7.4,Very Good,99 Total Reviews,Privates From\nRs3119,Dorms From\nRs1213,Free WiFiFollows Covid-19 sanitation guidance,Welcome to New Cross Inn Hostel!\n\nA Friendly...
14,New Cross Inn Hostel,Hostel - 6.1km from city centre,7.2,Very Good,1004 Total Reviews,Privates From\nRs4559,Dorms From\nRs1733,Free WiFiFree Breakfast,"Welcome to one of London's cheapest, friendlie..."
15,Strand Continental,Hostel - 1.3km from city centre,8.3,Fabulous,773 Total Reviews,Privates From\nRs4255,No Dorms Available,Free BreakfastFollows Covid-19 sanitation guid...,Looking for a Bed & Breakfast with the best pr...
16,St Christopher's Oasis-Female Only,Hostel - 1.8km from city centre,9.1,Superb,594 Total Reviews,No Privates Available,Dorms From\nRs1442,Free WiFiFollows Covid-19 sanitation guidance,COVID 19 Policy Update.\nIn response to Corona...
17,Astor Museum Inn,Hostel - 2.2km from city centre,9.5,Superb,8714 Total Reviews,No Privates Available,Dorms From\nRs1824,Free WiFiFollows Covid-19 sanitation guidance,With the British Museum literally on its doors...
18,Astor Kensington,Hostel - 4.9km from city centre,8.7,Fabulous,6326 Total Reviews,Privates From\nRs7295,Dorms From\nRs1520,Free WiFiFollows Covid-19 sanitation guidance,"Located a short walk from Notting Hill, Hyde P..."
19,Mapesbury Hostel,Hostel - 8.2km from city centre,-,Rating,357 Total Reviews,Privates From\nRs4559,No Dorms Available,Free WiFiFollows Covid-19 sanitation guidance,The Mapesbury Hostel offers budget accommodati...
20,Hootananny Hostel,Hostel - 5km from city centre,8.0,Fabulous,1406 Total Reviews,No Privates Available,Dorms From\nRs1636,Free WiFiFree Breakfast,Hootananny is a lively hostel with spacious ro...
21,Astor Hyde Park,Hostel - 4.3km from city centre,9.1,Superb,11326 Total Reviews,No Privates Available,Dorms From\nRs1520,Free WiFiFollows Covid-19 sanitation guidance,Located in the most beautiful and charming nei...
22,Phoenix Hostel,Hostel - 4.2km from city centre,8.3,Fabulous,3420 Total Reviews,Privates From\nRs2037,Dorms From\nRs1489,Free WiFi,*Please note we are operating on LIMITED recep...
23,247london Hostel and Private Rooms,Hostel - 8.2km from city centre,6.6,Good,443 Total Reviews,Privates From\nRs5167,No Dorms Available,Free WiFi,247london Hostel and Private Rooms is a home a...
24,Burlington Residence,Hostel - 7.1km from city centre,9.8,Superb,26 Total Reviews,Privates From\nRs4296,Dorms From\nRs2067,Free WiFiFree BreakfastFollows Covid-19 sanita...,"Situated in South West London, close to Balham..."
25,SoHostel,Hostel - 2km from city centre,8.6,Fabulous,3960 Total Reviews,No Privates Available,Dorms From\nRs2026,Free WiFiFollows Covid-19 sanitation guidance,We have implemented our Staying Safe Together ...
26,Clink261,Hostel - 3.2km from city centre,7.6,Very Good,3172 Total Reviews,Privates From\nRs5082,Dorms From\nRs1347,Free WiFiFollows Covid-19 sanitation guidance,"Clink261 is a comfortable, centrally located h..."
27,Generator London,Hostel - 3km from city centre,7.6,Very Good,6737 Total Reviews,Privates From\nRs8004,Dorms From\nRs1925,Free WiFiFollows Covid-19 sanitation guidance,Generator London is a design hotel-hostel loca...
28,"PubLove @ The White Ferry, Victoria",Hostel - 2.4km from city centre,8.9,Fabulous,134 Total Reviews,Privates From\nRs16414,Dorms From\nRs1368,Free WiFiFollows Covid-19 sanitation guidance,"Walk to the river, turn left, and just keep wa..."
29,Smart Russell Square Hostel,Hostel - 2.6km from city centre,7.3,Very Good,9503 Total Reviews,No Privates Available,Dorms From\nRs1160,Free WiFiFollows Covid-19 sanitation guidance,"Nestled in the heart of London, walking distan..."

# Write a python program to access the search bar and search button on images.google.com and scrape 100 images each for keywords ‘fruits’, ‘cars’ and ‘Machine Learning’

In [3]:
from selenium.common.exceptions import ElementClickInterceptedException,StaleElementReferenceException

In [4]:
driver.get("https://www.google.com")

In [5]:
ser=driver.find_element_by_xpath('//a[@data-pid="2"]')
ser.click()

In [6]:
search=driver.find_element_by_xpath('//input[@class="gLFyf gsfi"]')
search.send_keys('fruits')

In [7]:
btn=driver.find_element_by_xpath('//div[@class="zgAlFc"]')
btn.click()

In [8]:
fruit=[]
car=[]
ml=[]

In [45]:
images=driver.find_elements_by_xpath('//img[@class="rg_i Q4LuWd"]')

In [112]:
for i in images:
    i.click()
    
    try:
        for j in driver.find_elements_by_xpath('//img[@class="n3VNCb"]'):
            fruit.append(j.get_attribute('src'))
            
    except ElementClickInterceptedException:
          None

In [113]:
driver.get("https://www.google.com")
ser=driver.find_element_by_xpath('//a[@data-pid="2"]')
ser.click()
search=driver.find_element_by_xpath('//input[@class="gLFyf gsfi"]')
search.send_keys('cars')
btn=driver.find_element_by_xpath('//div[@class="zgAlFc"]')
btn.click()

In [114]:
images=driver.find_elements_by_xpath('//img[@class="rg_i Q4LuWd"]')

In [115]:
for i in images:
    i.click()
    
    try:
        for j in driver.find_elements_by_xpath('//img[@class="n3VNCb"]'):
            car.append(j.get_attribute('src'))
            
    except ElementClickInterceptedException:
          None

In [117]:
driver.get("https://www.google.com")
ser=driver.find_element_by_xpath('//a[@data-pid="2"]')
ser.click()
search=driver.find_element_by_xpath('//input[@class="gLFyf gsfi"]')
search.send_keys('machine learning')
btn=driver.find_element_by_xpath('//div[@class="zgAlFc"]')
btn.click()

In [118]:
images=driver.find_elements_by_xpath('//img[@class="rg_i Q4LuWd"]')

In [119]:
for i in images:
    i.click()
    
    try:
        for j in driver.find_elements_by_xpath('//img[@class="n3VNCb"]'):
            ml.append(j.get_attribute('src'))
            
    except ElementClickInterceptedException:
          None

In [120]:
df=pd.DataFrame({"Fruits":fruit[0:100],
                "Car":car[0:100],
                "Machine Learninng":ml[0:100]})

In [121]:
df

,Fruits,Car,Machine Learninng
0,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...",https://data-flair.training/blogs/wp-content/u...
1,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
2,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
3,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
4,"data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA...","data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQA..."
...,...,...,...
95,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://encrypted-tbn0.gstatic.com/images?q=tb...
96,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://encrypted-tbn0.gstatic.com/images?q=tb...
97,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://encrypted-tbn0.gstatic.com/images?q=tb...
98,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://encrypted-tbn0.gstatic.com/images?q=tb...
99,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://encrypted-tbn0.gstatic.com/images?q=tb...,https://encrypted-tbn0.gstatic.com/images?q=tb...

# Write a program to scrap geospatial coordinates (latitude, longitude) of a city searched on google maps.

In [64]:
import re

In [65]:
driver.get("http://maps.google.co.in")

In [66]:
search=driver.find_element_by_xpath('//input[@id="searchboxinput"]')

In [67]:
city=input("Enter a city : ")

Enter a city : mumbai

In [68]:
search.send_keys(city)

In [72]:
driver.find_element_by_xpath('//button[@id="searchbox-searchbutton"]').click()

In [73]:
url_string=driver.current_url

In [74]:
lat_lng = re.findall(r'@(.*)data',url_string)
lat_lng

['19.0821978,72.7410991,11z/']